-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/{{ cookiecutter.repo_name }}/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes

-- (This is a placeholder until the tables are first generated)